var LANGUAGE_NAMES={"auto":"Auto","zh-Hans":"Simplified Chinese","zh-Hant":"Traditional Chinese","yue":"Cantonese","wyw":"Classical Chinese","en":"English","ja":"Japanese","ko":"Korean","fr":"French","de":"German","es":"Spanish","it":"Italian","ru":"Russian","pt":"Portuguese","pt-pt":"Portuguese (Portugal)","pt-br":"Portuguese (Brazil)","nl":"Dutch","pl":"Polish","ar":"Arabic","tr":"Turkish","th":"Thai","vi":"Vietnamese","id":"Indonesian","ms":"Malay","hi":"Hindi","uk":"Ukrainian"};
function supportLanguages(){return Object.keys(LANGUAGE_NAMES);}
function pluginTimeoutInterval(){return 120;}
function trim(v){return v===undefined||v===null?"":String(v).replace(/^\s+|\s+$/g,"");}
function lang(c){return LANGUAGE_NAMES[c]||c||"Auto";}
function renderString(s,v){return String(s).split("{{from}}").join(v.from).split("{{to}}").join(v.to).split("{{text}}").join(v.text).split("{{model}}").join(v.model).split("{{format}}").join(v.format).split("{{prompt}}").join(v.prompt||"");}
function renderAny(x,v){if(typeof x==="string")return renderString(x,v);if(Array.isArray(x))return x.map(function(i){return renderAny(i,v);});if(x&&typeof x==="object"){var o={};Object.keys(x).forEach(function(k){o[k]=renderAny(x[k],v);});return o;}return x;}
function parseObj(raw,label){var s=trim(raw);if(!s)return {};var x;try{x=JSON.parse(s);}catch(e){throw new Error(label+" JSON 格式错误："+e.message);}if(!x||typeof x!=="object"||Array.isArray(x))throw new Error(label+" 必须是 JSON 对象");return x;}
function merge(a,b){Object.keys(b||{}).forEach(function(k){a[k]=b[k];});return a;}
function setHeader(h,n,v){var l=n.toLowerCase();Object.keys(h).forEach(function(k){if(k.toLowerCase()===l&&k!==n)delete h[k];});h[n]=v;}
function mergeHeaders(h,b){Object.keys(b||{}).forEach(function(k){setHeader(h,k,b[k]);});return h;}
function splitSuffix(u){var q=u.indexOf("?"),h=u.indexOf("#"),i=-1;if(q>=0&&h>=0)i=Math.min(q,h);else if(q>=0)i=q;else if(h>=0)i=h;return i<0?{base:u,suffix:""}:{base:u.slice(0,i),suffix:u.slice(i)};}
function pathOf(u){var m=String(u).match(/^https?:\/\/[^\/]+(\/.*)?$/i);return m?(m[1]||""):"";}
function endpoint(url,format,mode){var raw=trim(url);if(!raw)throw new Error("请填写 API 地址");if(mode==="manual")return raw;var p=splitSuffix(raw),b=p.base,s=p.suffix;while(b.length>1&&b.charAt(b.length-1)==="/")b=b.slice(0,-1);
  if(format==="chat"){if(/\/chat\/completions$/i.test(b))return b+s;var pth=pathOf(b);if(!pth)return b+"/v1/chat/completions"+s;return b+"/chat/completions"+s;}
  if(format==="responses"){if(/\/responses$/i.test(b))return b+s;var pth2=pathOf(b);if(!pth2)return b+"/v1/responses"+s;return b+"/responses"+s;}
  if(/\/messages$/i.test(b))return b+s;var pth3=pathOf(b);if(!pth3)return b+"/v1/messages"+s;return b+"/messages"+s;
}
function posInt(raw,d,label){var s=trim(raw);if(!s)return d;var n=Number(s);if(!isFinite(n)||n<=0||Math.floor(n)!==n)throw new Error(label+" 必须是正整数");return n;}
function promptData(q,format,model){var text=q.originalText||q.text||"",vars={from:lang(q.detectFrom||q.from||"auto"),to:lang(q.detectTo||q.to||"zh-Hans"),text:text,model:model,format:format,prompt:""};var tpl=trim($option.prompt)||"Translate the user's text from {{from}} to {{to}}. Preserve formatting. Output only the translation.";var prompt=renderString(tpl,vars);vars.prompt=prompt;return {text:text,prompt:prompt,vars:vars};}
function bodyFor(format,model,p,stream){if(format==="chat")return {model:model,messages:[{role:"system",content:p.prompt},{role:"user",content:p.text}],stream:stream};if(format==="responses")return {model:model,instructions:p.prompt,input:p.text,stream:stream};return {model:model,system:p.prompt,messages:[{role:"user",content:p.text}],max_tokens:posInt($option.claudeMaxTokens,2048,"Claude max_tokens"),stream:stream};}
function headersFor(format,key,stream){var h={"Content-Type":"application/json"};if(key){if(format==="claude")h["x-api-key"]=key;else h["Authorization"]="Bearer "+key;}if(format==="claude")h["anthropic-version"]=trim($option.anthropicVersion)||"2023-06-01";if(stream)h["Accept"]="text/event-stream";return h;}
function statusOf(r){if(r&&r.response&&r.response.statusCode!==undefined)return Number(r.response.statusCode);if(r&&r.statusCode!==undefined)return Number(r.statusCode);return 0;}
function apiError(d,f){if(d&&d.error){if(typeof d.error==="string")return d.error;if(d.error.message)return d.error.message;try{return JSON.stringify(d.error);}catch(e){}}if(d&&d.detail){if(typeof d.detail==="string")return d.detail;try{return JSON.stringify(d.detail);}catch(e2){}}if(d&&d.message)return String(d.message);if(typeof d==="string"){var t=trim(d);if(!t)return f||"API 请求失败";try{return apiError(JSON.parse(t),f);}catch(e3){if(/^<!doctype html/i.test(t)||/^<html/i.test(t))return "上游返回 HTML 页面：当前 URL 很可能指向网站首页/管理后台，而不是真实 API 接口。请检查 API 地址，或切换为“完整 URL 原样使用”。";return t.length>500?t.slice(0,500)+"…":t;}}return f||"API 请求失败";}
function textPart(v){if(typeof v==="string")return v;if(!Array.isArray(v))return "";var a=[];v.forEach(function(x){if(!x)return;if(typeof x==="string")a.push(x);else if(typeof x.text==="string")a.push(x.text);else if(typeof x.content==="string")a.push(x.content);});return a.join("");}
function extract(format,d){if(d===undefined||d===null)return "";if(typeof d==="string"){var t=trim(d);if(!t)return "";try{return extract(format,JSON.parse(t));}catch(e){return d;}}
  if(format==="chat"&&d.choices&&d.choices[0]){var c=d.choices[0];if(c.message){var x=textPart(c.message.content);if(x)return x;}if(typeof c.text==="string")return c.text;}
  if(format==="responses"){if(typeof d.output_text==="string")return d.output_text;var a=[];(d.output||[]).forEach(function(i){if(!i)return;if(typeof i.text==="string"&&(i.type==="output_text"||i.type==="text"))a.push(i.text);(i.content||[]).forEach(function(p){if(p&&typeof p.text==="string"&&(p.type==="output_text"||p.type==="text"||!p.type))a.push(p.text);});});if(a.length)return a.join("");}
  if(format==="claude"&&Array.isArray(d.content)){var ca=[];d.content.forEach(function(b){if(b&&b.type==="text"&&typeof b.text==="string")ca.push(b.text);});if(ca.length)return ca.join("");}
  if(d.choices&&d.choices[0]&&d.choices[0].message){var fc=textPart(d.choices[0].message.content);if(fc)return fc;}if(typeof d.output_text==="string")return d.output_text;if(Array.isArray(d.content)){var fb=[];d.content.forEach(function(b){if(b&&typeof b.text==="string")fb.push(b.text);});if(fb.length)return fb.join("");}return "";
}
function done(q,c,p){if(q&&typeof q.onCompletion==="function")q.onCompletion(p);else if(typeof c==="function")c(p);}
function result(text,q,raw){var r={toParagraphs:[text],from:q.detectFrom||q.from,to:q.detectTo||q.to};if(raw!==undefined)r.raw=raw;return r;}
function build(q){var format=trim($option.apiFormat||"chat");if(["chat","responses","claude"].indexOf(format)<0)throw new Error("API 格式无效");var model=trim($option.model);if(!model)throw new Error("请填写模型名称");var stream=String($option.stream||"true")==="true",p=promptData(q,format,model),body=bodyFor(format,model,p,stream);merge(body,renderAny(parseObj($option.customBody,"自定义请求参数"),p.vars));var finalStream=body.stream===true,h=headersFor(format,trim($option.apiKey),finalStream);mergeHeaders(h,renderAny(parseObj($option.customHeaders,"自定义请求头"),p.vars));return {format:format,url:endpoint($option.apiURL,format,trim($option.urlMode||"auto")),headers:h,body:body,stream:finalStream};}
function translate(q,c){var r;try{r=build(q);}catch(e){done(q,c,{error:{type:"param",message:e.message}});return;}if(r.stream)streamTranslate(q,c,r);else once(q,c,r);}
function once(q,c,r){$http.request({method:"POST",url:r.url,header:r.headers,body:r.body,timeout:120,cancelSignal:q.cancelSignal,handler:function(resp){if(resp&&resp.error){done(q,c,{error:{type:"network",message:resp.error.message||String(resp.error)}});return;}var s=statusOf(resp),d=resp?resp.data:null;if(s&&(s<200||s>=300)){done(q,c,{error:{type:s===401||s===403?"secretKey":"api",message:"HTTP "+s+"："+apiError(d,"请求失败"),addition:d}});return;}if(d&&d.error){done(q,c,{error:{type:"api",message:apiError(d,"API 返回错误"),addition:d}});return;}var out=extract(r.format,d);if(!out){done(q,c,{error:{type:"api",message:"未从响应中识别到翻译文本。",addition:d}});return;}done(q,c,{result:result(out,q,d)});}});}
function streamTranslate(q,c,r){var buf="",out="",err=null,last=null,finished=false,plain="";function finish(x){if(finished)return;finished=true;done(q,c,x);}function emit(){if(out&&q&&typeof q.onStream==="function")q.onStream(result(out,q));}function add(t){if(typeof t==="string"&&t){out+=t;emit();}}function handle(o,event){if(!o)return;last=o;var type=o.type||event||"";if(o.error||type==="error"||type==="response.failed"){err=apiError(o,"流式请求失败");return;}if(r.format==="chat"&&o.choices&&o.choices[0]&&o.choices[0].delta){var x=o.choices[0].delta.content;if(typeof x==="string")add(x);else if(Array.isArray(x))add(textPart(x));return;}if(r.format==="responses"&&type==="response.output_text.delta"){add(typeof o.delta==="string"?o.delta:o.text);return;}if(r.format==="responses"&&type==="response.output_text.done"){if(!out&&typeof o.text==="string")add(o.text);return;}if(r.format==="claude"&&type==="content_block_delta"&&o.delta&&o.delta.type==="text_delta"){add(o.delta.text);return;}if(r.format==="claude"&&type==="content_block_start"&&o.content_block&&o.content_block.type==="text")add(o.content_block.text);if(!out){var full=extract(r.format,o);if(full)add(full);}}
 function frame(f){var t=trim(f);if(!t)return;var ev="",ds=[];t.split("\n").forEach(function(l){if(l.indexOf("event:")===0)ev=trim(l.slice(6));else if(l.indexOf("data:")===0)ds.push(l.slice(5).replace(/^\s+/,""));});var d=ds.join("\n");if(d){if(trim(d)==="[DONE]")return;try{handle(JSON.parse(d),ev);}catch(e){}return;}if(t.charAt(0)==="{"){try{handle(JSON.parse(t),ev);return;}catch(e2){}}plain+=t;}
 function consume(ch){if(!ch)return;buf+=ch;buf=buf.replace(/\r\n/g,"\n");var i;while((i=buf.indexOf("\n\n"))!==-1){frame(buf.slice(0,i));buf=buf.slice(i+2);}}
 $http.streamRequest({method:"POST",url:r.url,header:r.headers,body:r.body,timeout:120,cancelSignal:q.cancelSignal,streamHandler:function(s){if(s&&s.text)consume(s.text);},handler:function(resp){if(trim(buf)){frame(buf);buf="";}if(resp&&resp.error){finish({error:{type:"network",message:resp.error.message||String(resp.error)}});return;}var st=statusOf(resp),d=resp?resp.data:null;if(!err&&st>=400&&d)err=apiError(d,"");if(!err&&plain&&st>=400)err=apiError(plain,"");if(st&&(st<200||st>=300)){finish({error:{type:st===401||st===403?"secretKey":"api",message:"HTTP "+st+"："+(err||apiError(d,"请求失败")),addition:last||d||plain}});return;}if(err){finish({error:{type:"api",message:err,addition:last||d||plain}});return;}if(!out&&d){var f=extract(r.format,d);if(f){out=f;emit();}}if(!out){finish({error:{type:"api",message:"流式请求完成，但没有识别到文本内容。可关闭流式输出检查完整响应，或确认 API 格式与 URL。",addition:last||d||plain}});return;}finish({result:result(out,q,last||d)});}});}
function pluginValidate(c){try{var f=trim($option.apiFormat||"chat");if(["chat","responses","claude"].indexOf(f)<0)throw new Error("API 格式无效");if(!trim($option.apiURL))throw new Error("请填写 API 地址");if(!trim($option.model))throw new Error("请填写模型名称");endpoint($option.apiURL,f,trim($option.urlMode||"auto"));if(f==="claude")posInt($option.claudeMaxTokens,2048,"Claude max_tokens");parseObj($option.customBody,"自定义请求参数");parseObj($option.customHeaders,"自定义请求头");c({result:true});}catch(e){c({result:false,error:{type:"param",message:e.message}});}}
